# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

"""DTensor-based tests for 1D CP confidence loss.

Tests the 1D CP confidence loss sub-functions (resolved_loss_1d, plddt_loss_1d,
pde_loss_1d, pae_loss_1d) and the top-level aggregator (confidence_loss_1d)
against their serial equivalents from boltz.model.loss.confidencev2.

Maps to: src/boltz/distributed/model/loss/confidence_1d.py

Test strategy:
  - Generate random features on CPU using ``random_features``.
  - Compute serial loss + gradient as reference.
  - Distribute features to the 2D mesh (dp, cp) with 1D CP placements.
  - Compute distributed loss + gradient.
  - Assert forward parity (loss value), backward parity (pred gradient),
    non-vacuousness (non-zero gradients), and immutability (inputs unchanged).
"""

import pytest
import torch
from torch.distributed.tensor import Replicate, Shard, distribute_tensor

from boltz.distributed.manager import DistributedManager
from boltz.distributed.model.loss.confidence_1d import (
    _compute_frame_pred_1d,
    confidence_loss_1d,
    pde_loss_1d,
    plddt_loss_1d,
    resolved_loss_1d,
)
from boltz.model.layers.confidence_utils import compute_frame_pred as serial_compute_frame_pred
from boltz.model.loss.confidencev2 import confidence_loss as serial_confidence_loss
from boltz.model.loss.confidencev2 import pde_loss as serial_pde_loss
from boltz.model.loss.confidencev2 import plddt_loss as serial_plddt_loss
from boltz.model.loss.confidencev2 import resolved_loss as serial_resolved_loss
from boltz.testing.utils import (
    init_tensors_uniform,
    random_features,
    skip_if_cuda_not_avail_or_device_count_less_than_word_size,
    spawn_multiprocessing,
)

SEED = 42

# 1D CP placements
_SINGLE = (Shard(0), Shard(1))  # [B, N, ...]
_ATOM = (Shard(0), Replicate())  # [B, N_atom, ...] — canonical (pre-694573d2)
_ATOM_SHARDED = (Shard(0), Shard(1))  # [B, N_atom, ...] — post-694573d2 sharded variant
_REPLICATED = (Replicate(), Replicate())


def _generate_test_data(cp_size: int, multiplicity: int = 1, rng_seed: int = SEED):
    """Generate serial test data suitable for 1D CP confidence tests.

    Returns
    -------
    feats : dict[str, Tensor]
        Feature tensors generated by random_features.
    model_out : dict[str, Tensor]
        Model output tensors (logits + coords).
    true_coords : Tensor
    true_coords_resolved_mask : Tensor
    d_loss : Tensor
        Random grad_output for backward.
    """
    B = 2
    n_tokens = 12 * cp_size  # must be divisible by cp_size
    n_atoms = n_tokens  # 1 atom per token for simplicity
    n_msa = 4
    bins_lddt = 50
    bins_pde = 64
    bins_pae = 64

    rng = torch.Generator()
    rng.manual_seed(rng_seed)

    feats = random_features(
        size_batch=B,
        n_tokens=n_tokens,
        n_atoms=n_atoms,
        n_msa=n_msa,
        atom_counts_per_token_range=(1, 1),
        device=torch.device("cpu"),
        float_value_range=(-0.5, 0.5),
        rng=rng,
        cp_size=cp_size,
    )
    # Cast float64 features to float32 for loss computation
    for k, v in feats.items():
        if v.dtype == torch.float64:
            feats[k] = v.float()

    # Model outputs — repeat batch for multiplicity
    pred_lddt = torch.randn(B * multiplicity, n_tokens, bins_lddt, generator=rng)
    pred_pde = torch.randn(B * multiplicity, n_tokens, n_tokens, bins_pde, generator=rng)
    pred_resolved = torch.randn(B * multiplicity, n_tokens, 2, generator=rng)
    pred_pae = torch.randn(B * multiplicity, n_tokens, n_tokens, bins_pae, generator=rng)
    sample_atom_coords = torch.randn(B * multiplicity, n_atoms, 3, generator=rng)

    model_out = {
        "plddt_logits": pred_lddt,
        "pde_logits": pred_pde,
        "resolved_logits": pred_resolved,
        "pae_logits": pred_pae,
        "sample_atom_coords": sample_atom_coords,
    }

    true_coords = torch.randn(B * multiplicity, n_atoms, 3, generator=rng)
    true_coords_resolved_mask = feats["atom_resolved_mask"].repeat_interleave(multiplicity, dim=0).float()

    d_loss = torch.empty(())
    init_tensors_uniform([d_loss], low=-0.5, high=0.5)

    return feats, model_out, true_coords, true_coords_resolved_mask, d_loss


def _distribute_feats_1d(feats, device_mesh, device, atom_pl=_ATOM):
    """Distribute feature dict to 2D mesh with 1D CP placements.

    Token-level features: (Shard(0), Shard(1))
    Atom-level features: ``atom_pl`` (default (Shard(0), Replicate()); pass
    ``_ATOM_SHARDED`` to exercise the wrapper-level redistribute path for
    callers that pass post-694573d2 (Shard(0), Shard(1)) atom placements).
    """
    # Categorize features by their sharding pattern
    atom_keys = {
        "atom_pad_mask",
        "atom_resolved_mask",
        "atom_to_token",
        "atom_counts_per_token",
    }
    # These are token-level features that should be sharded on dim 1
    single_keys = {
        "token_to_rep_atom",
        "r_set_to_rep_atom",
        "token_pad_mask",
        "mol_type",
        "asym_id",
        "frame_resolved_mask",
        "frames_idx",
    }

    distributed = {}
    for k, v in feats.items():
        t = v.to(device)
        if k in atom_keys:
            distributed[k] = distribute_tensor(t, device_mesh, atom_pl)
        elif k in single_keys:
            distributed[k] = distribute_tensor(t, device_mesh, _SINGLE)
        else:
            # Default: try single placement if 2D+ with token dim, else replicate
            if t.ndim >= 2 and t.shape[1] == feats["token_pad_mask"].shape[1]:
                distributed[k] = distribute_tensor(t, device_mesh, _SINGLE)
            else:
                distributed[k] = distribute_tensor(t, device_mesh, atom_pl)
    return distributed


# ---------------------------------------------------------------------------
# Worker functions (run on each rank)
# ---------------------------------------------------------------------------


def _worker_compute_frame_pred_1d(rank, payload):
    """Worker: _compute_frame_pred_1d parity with serial compute_frame_pred."""
    (
        grid_group_sizes,
        device_type,
        backend,
        env_per_rank,
        multiplicity,
        pred_atom_coords_host,
        feats_host,
        expected_frames_idx_host,
        expected_mask_collinear_host,
    ) = payload

    monkeypatch = pytest.MonkeyPatch()
    if env_per_rank is not None:
        for var_name, value in env_per_rank.items():
            if value == "<INPUT_RANK>":
                monkeypatch.setenv(var_name, f"{rank}")
                continue
            monkeypatch.setenv(var_name, value)

    DistributedManager.initialize(grid_group_sizes, device_type=device_type, backend=backend)
    dm = DistributedManager()
    device_mesh = dm.device_mesh
    device = dm.device

    # Distribute atom coords: [B*mult, N_atom, 3] -> atom placement (Shard(0), Replicate())
    pred_coords_dt = distribute_tensor(pred_atom_coords_host.to(device), device_mesh, _ATOM)
    # Distribute frames_idx: [B, N_token, 3] -> single placement (Shard(0), Shard(1))
    frames_idx_dt = distribute_tensor(feats_host["frames_idx"].to(device), device_mesh, _SINGLE)
    feats_dt = _distribute_feats_1d(feats_host, device_mesh, device)

    frames_idx_pred, mask_collinear_pred = _compute_frame_pred_1d(
        pred_atom_coords=pred_coords_dt,
        frames_idx_true=frames_idx_dt,
        feats=feats_dt,
        multiplicity=multiplicity,
        device_mesh=device_mesh,
    )

    # --- Compare frames_idx_pred via geometry proxy ---
    # _compute_frame_pred_1d returns [B, mult, N, 3] with (Shard(0), Shard(2))
    # Gather to full for comparison
    size_batch = feats_host["atom_pad_mask"].shape[0]
    _, num_tokens = feats_host["asym_id"].shape

    replicate_pl = (Replicate(), Replicate())
    frames_idx_pred_full = frames_idx_pred.redistribute(device_mesh, placements=replicate_pl).to_local()

    pred_coords_local = pred_atom_coords_host.to(device).unflatten(0, (size_batch, multiplicity))
    expected_frames_idx_local = expected_frames_idx_host.to(device)

    batch_idx = torch.arange(size_batch, device=device)[:, None, None, None]
    mult_idx = torch.arange(multiplicity, device=device)[None, :, None, None]

    dt_frames = pred_coords_local[batch_idx, mult_idx, frames_idx_pred_full]
    host_frames = pred_coords_local[batch_idx, mult_idx, expected_frames_idx_local]

    # Use mean frame center as an index-invariant proxy
    dt_frame_centers = dt_frames.mean(dim=-2)
    host_frame_centers = host_frames.mean(dim=-2)

    token_pad_mask_bool = feats_host["token_pad_mask"].bool().to(device)
    for batch_i in range(size_batch):
        valid = token_pad_mask_bool[batch_i]
        assert valid.any(), f"batch {batch_i} has no valid tokens"
        torch.testing.assert_close(
            dt_frame_centers[batch_i, :, valid].cpu(),
            host_frame_centers[batch_i, :, valid].cpu(),
            msg=lambda m: f"Rank {rank} frames_idx_pred mismatch\n{m}",
        )

    # --- Compare mask_collinear ---
    mask_collinear_full = mask_collinear_pred.full_tensor().cpu()
    expected_mask_cpu = expected_mask_collinear_host.cpu()

    for batch_i in range(mask_collinear_full.shape[0]):
        valid = feats_host["token_pad_mask"][batch_i].bool()
        actual_valid = mask_collinear_full[batch_i, :, valid]
        expected_valid = expected_mask_cpu[batch_i, :, valid]

        # Non-vacuous: at least some collinear entries on valid tokens
        assert actual_valid.any() or expected_valid.any(), (
            f"batch {batch_i} mask_collinear on valid tokens is always False for both "
            "actual and expected — test is vacuous"
        )

        torch.testing.assert_close(
            actual_valid,
            expected_valid,
            msg=lambda m: f"Rank {rank} mask_collinear mismatch batch {batch_i}\n{m}",
        )

    DistributedManager.cleanup()
    monkeypatch.undo()


def _worker_resolved_loss_1d(rank, payload):
    """Worker: resolved_loss_1d parity with serial."""
    (
        grid_group_sizes,
        device_type,
        backend,
        env_per_rank,
        pred_resolved_host,
        feats_host,
        true_coords_resolved_mask_host,
        expected_loss,
        expected_pred_grad,
        d_loss_host,
        multiplicity,
        atom_pl,
    ) = payload

    monkeypatch = pytest.MonkeyPatch()
    if env_per_rank is not None:
        for var_name, value in env_per_rank.items():
            if value == "<INPUT_RANK>":
                monkeypatch.setenv(var_name, f"{rank}")
                continue
            monkeypatch.setenv(var_name, value)

    DistributedManager.initialize(grid_group_sizes, device_type=device_type, backend=backend)
    dm = DistributedManager()
    device_mesh = dm.device_mesh
    device = dm.device

    pred_dt = distribute_tensor(pred_resolved_host.to(device), device_mesh, _SINGLE).requires_grad_(True)
    mask_dt = distribute_tensor(true_coords_resolved_mask_host.to(device), device_mesh, atom_pl)
    feats_dt = _distribute_feats_1d(feats_host, device_mesh, device, atom_pl=atom_pl)

    dp_group = device_mesh.get_group("dp")
    cp_group = device_mesh.get_group("cp")

    loss_dt = resolved_loss_1d(
        pred_resolved=pred_dt,
        feats=feats_dt,
        true_coords_resolved_mask=mask_dt,
        device_mesh=device_mesh,
        dp_group=dp_group,
        cp_group=cp_group,
        multiplicity=multiplicity,
    )

    # Forward parity
    loss_val = loss_dt.full_tensor().item()
    # fp32 defaults: per-element BCE mean reduction (N=B*n_tokens*2 ~144) with one packed all_reduce; no cp-reorder.
    torch.testing.assert_close(
        torch.tensor(loss_val),
        torch.tensor(expected_loss),
        msg=lambda m: f"Rank {rank} resolved loss mismatch\n{m}",
    )

    # Backward
    d_loss_dt = distribute_tensor(d_loss_host.to(device), device_mesh, _REPLICATED)
    loss_dt.backward(d_loss_dt)

    assert pred_dt.grad is not None, "pred gradient is None"
    pred_grad_full = pred_dt.grad.full_tensor()
    # fp32 defaults: per-element BCE backward (identity through all_reduce); no cp-reorder, single packed all_reduce.
    torch.testing.assert_close(
        pred_grad_full.cpu(),
        expected_pred_grad,
        msg=lambda m: f"Rank {rank} resolved grad mismatch\n{m}",
    )

    # Non-vacuous
    assert pred_grad_full.abs().sum() > 0, "Gradient is all-zero"

    DistributedManager.cleanup()
    monkeypatch.undo()


def _worker_plddt_loss_1d(rank, payload):
    """Worker: plddt_loss_1d parity with serial."""
    (
        grid_group_sizes,
        device_type,
        backend,
        env_per_rank,
        pred_lddt_host,
        pred_atom_coords_host,
        true_atom_coords_host,
        true_coords_resolved_mask_host,
        feats_host,
        expected_loss,
        expected_pred_grad,
        d_loss_host,
        multiplicity,
        atom_pl,
    ) = payload

    monkeypatch = pytest.MonkeyPatch()
    if env_per_rank is not None:
        for var_name, value in env_per_rank.items():
            if value == "<INPUT_RANK>":
                monkeypatch.setenv(var_name, f"{rank}")
                continue
            monkeypatch.setenv(var_name, value)

    DistributedManager.initialize(grid_group_sizes, device_type=device_type, backend=backend)
    dm = DistributedManager()
    device_mesh = dm.device_mesh
    device = dm.device

    pred_dt = distribute_tensor(pred_lddt_host.to(device), device_mesh, _SINGLE).requires_grad_(True)
    pred_coords_dt = distribute_tensor(pred_atom_coords_host.to(device), device_mesh, atom_pl)
    true_coords_dt = distribute_tensor(true_atom_coords_host.to(device), device_mesh, atom_pl)
    mask_dt = distribute_tensor(true_coords_resolved_mask_host.to(device), device_mesh, atom_pl)
    feats_dt = _distribute_feats_1d(feats_host, device_mesh, device, atom_pl=atom_pl)

    dp_group = device_mesh.get_group("dp")
    cp_group = device_mesh.get_group("cp")

    loss_dt = plddt_loss_1d(
        pred_lddt=pred_dt,
        pred_atom_coords=pred_coords_dt,
        true_atom_coords=true_coords_dt,
        true_coords_resolved_mask=mask_dt,
        feats=feats_dt,
        device_mesh=device_mesh,
        dp_group=dp_group,
        cp_group=cp_group,
        multiplicity=multiplicity,
    )

    # Forward parity
    # pLDDT loss uses floor(target_lddt * num_bins) to quantize into bins.
    # With cp>1, all-reduce ordering differences cause O(eps) shifts in
    # target_lddt, which can move it across a bin boundary.  The resulting
    # one-hot target changes discretely, producing O(1/num_bins) ~ 0.02
    # absolute loss error.  We relax tolerance accordingly for cp>1.
    cp_size = grid_group_sizes["cp"]
    loss_atol = 0.01 if cp_size > 1 else 1e-4
    loss_rtol = 0.01 if cp_size > 1 else 1e-4
    loss_val = loss_dt.full_tensor().item()
    torch.testing.assert_close(
        torch.tensor(loss_val),
        torch.tensor(expected_loss),
        atol=loss_atol,
        rtol=loss_rtol,
        msg=lambda m: f"Rank {rank} plddt loss mismatch\n{m}",
    )

    # Backward
    # Grad tolerance relaxed for cp>1: bin quantization sensitivity in the
    # forward propagates through cross-entropy backward into logit gradients.
    grad_atol = 0.02 if cp_size > 1 else 5e-4
    grad_rtol = 0.02 if cp_size > 1 else 5e-4
    d_loss_dt = distribute_tensor(d_loss_host.to(device), device_mesh, _REPLICATED)
    loss_dt.backward(d_loss_dt)

    assert pred_dt.grad is not None, "pred gradient is None"
    pred_grad_full = pred_dt.grad.full_tensor()
    torch.testing.assert_close(
        pred_grad_full.cpu(),
        expected_pred_grad,
        atol=grad_atol,
        rtol=grad_rtol,
        msg=lambda m: f"Rank {rank} plddt grad mismatch\n{m}",
    )

    # Non-vacuous
    assert pred_grad_full.abs().sum() > 0, "Gradient is all-zero"

    DistributedManager.cleanup()
    monkeypatch.undo()


def _worker_pde_loss_1d(rank, payload):
    """Worker: pde_loss_1d parity with serial."""
    (
        grid_group_sizes,
        device_type,
        backend,
        env_per_rank,
        pred_pde_host,
        pred_atom_coords_host,
        true_atom_coords_host,
        true_coords_resolved_mask_host,
        feats_host,
        expected_loss,
        expected_pred_grad,
        d_loss_host,
        multiplicity,
        atom_pl,
    ) = payload

    monkeypatch = pytest.MonkeyPatch()
    if env_per_rank is not None:
        for var_name, value in env_per_rank.items():
            if value == "<INPUT_RANK>":
                monkeypatch.setenv(var_name, f"{rank}")
                continue
            monkeypatch.setenv(var_name, value)

    DistributedManager.initialize(grid_group_sizes, device_type=device_type, backend=backend)
    dm = DistributedManager()
    device_mesh = dm.device_mesh
    device = dm.device

    pred_dt = distribute_tensor(pred_pde_host.to(device), device_mesh, _SINGLE).requires_grad_(True)
    pred_coords_dt = distribute_tensor(pred_atom_coords_host.to(device), device_mesh, atom_pl)
    true_coords_dt = distribute_tensor(true_atom_coords_host.to(device), device_mesh, atom_pl)
    mask_dt = distribute_tensor(true_coords_resolved_mask_host.to(device), device_mesh, atom_pl)
    feats_dt = _distribute_feats_1d(feats_host, device_mesh, device, atom_pl=atom_pl)

    dp_group = device_mesh.get_group("dp")
    cp_group = device_mesh.get_group("cp")

    loss_dt = pde_loss_1d(
        pred_pde=pred_dt,
        pred_atom_coords=pred_coords_dt,
        true_atom_coords=true_coords_dt,
        true_coords_resolved_mask=mask_dt,
        feats=feats_dt,
        device_mesh=device_mesh,
        dp_group=dp_group,
        cp_group=cp_group,
        multiplicity=multiplicity,
    )

    # Forward parity
    loss_val = loss_dt.full_tensor().item()
    # fp32 defaults: per-pair CE mean reduction (N=B*n_tokens^2*64 ~1.66e5) with one packed all_reduce; no cp-reorder.
    torch.testing.assert_close(
        torch.tensor(loss_val),
        torch.tensor(expected_loss),
        msg=lambda m: f"Rank {rank} pde loss mismatch\n{m}",
    )

    # Backward
    d_loss_dt = distribute_tensor(d_loss_host.to(device), device_mesh, _REPLICATED)
    loss_dt.backward(d_loss_dt)

    assert pred_dt.grad is not None, "pred gradient is None"
    pred_grad_full = pred_dt.grad.full_tensor()
    # fp32 defaults: per-pair CE backward (identity through all_reduce); no cp-reorder, single packed all_reduce.
    torch.testing.assert_close(
        pred_grad_full.cpu(),
        expected_pred_grad,
        msg=lambda m: f"Rank {rank} pde grad mismatch\n{m}",
    )

    # Non-vacuous
    assert pred_grad_full.abs().sum() > 0, "Gradient is all-zero"

    DistributedManager.cleanup()
    monkeypatch.undo()


def _worker_confidence_loss_1d(rank, payload):
    """Worker: confidence_loss_1d aggregator parity with serial."""
    (
        grid_group_sizes,
        device_type,
        backend,
        env_per_rank,
        model_out_host,
        feats_host,
        true_coords_host,
        true_coords_resolved_mask_host,
        expected_loss,
        expected_grads,
        d_loss_host,
        multiplicity,
        alpha_pae,
        atom_pl,
    ) = payload

    monkeypatch = pytest.MonkeyPatch()
    if env_per_rank is not None:
        for var_name, value in env_per_rank.items():
            if value == "<INPUT_RANK>":
                monkeypatch.setenv(var_name, f"{rank}")
                continue
            monkeypatch.setenv(var_name, value)

    DistributedManager.initialize(grid_group_sizes, device_type=device_type, backend=backend)
    dm = DistributedManager()
    device_mesh = dm.device_mesh
    device = dm.device

    # Distribute model outputs
    model_out_dt = {}
    grad_keys = []
    for k, v in model_out_host.items():
        t = v.detach().to(device)
        if k in ("sample_atom_coords",):
            model_out_dt[k] = distribute_tensor(t, device_mesh, atom_pl)
        else:
            dt = distribute_tensor(t, device_mesh, _SINGLE)
            if v.requires_grad:
                dt = dt.requires_grad_(True)
                grad_keys.append(k)
            model_out_dt[k] = dt

    true_coords_dt = distribute_tensor(true_coords_host.to(device), device_mesh, atom_pl)
    mask_dt = distribute_tensor(true_coords_resolved_mask_host.to(device), device_mesh, atom_pl)
    feats_dt = _distribute_feats_1d(feats_host, device_mesh, device, atom_pl=atom_pl)

    dp_group = device_mesh.get_group("dp")
    cp_group = device_mesh.get_group("cp")

    result = confidence_loss_1d(
        model_out=model_out_dt,
        feats=feats_dt,
        true_coords=true_coords_dt,
        true_coords_resolved_mask=mask_dt,
        device_mesh=device_mesh,
        dp_group=dp_group,
        cp_group=cp_group,
        token_level_confidence=True,
        multiplicity=multiplicity,
        alpha_pae=alpha_pae,
    )

    loss_dt = result["loss"]

    # Forward parity
    # The aggregated confidence loss includes plddt_loss which has bin
    # quantization sensitivity: floor(target_lddt * num_bins) can shift across
    # bin boundaries under all-reduce FP ordering differences (cp>1),
    # producing O(1/num_bins) ~ 0.02 absolute error per sub-loss component.
    cp_size = grid_group_sizes["cp"]
    loss_atol = 0.01 if cp_size > 1 else 1e-3
    loss_rtol = 0.01 if cp_size > 1 else 1e-3
    loss_val = loss_dt.full_tensor().item()
    torch.testing.assert_close(
        torch.tensor(loss_val),
        torch.tensor(expected_loss),
        atol=loss_atol,
        rtol=loss_rtol,
        msg=lambda m: f"Rank {rank} confidence loss mismatch\n{m}",
    )

    # Verify loss_breakdown keys
    breakdown = result["loss_breakdown"]
    for expected_key in ["plddt_loss", "pde_loss", "resolved_loss", "pae_loss"]:
        assert expected_key in breakdown, f"Missing key '{expected_key}' in loss_breakdown"

    # Backward
    # Grad tolerance relaxed for cp>1: plddt bin quantization sensitivity
    # cascades through backward into logit gradients for plddt_logits.
    grad_atol = 0.02 if cp_size > 1 else 5e-3
    grad_rtol = 0.02 if cp_size > 1 else 5e-3
    d_loss_dt = distribute_tensor(d_loss_host.to(device), device_mesh, _REPLICATED)
    loss_dt.backward(d_loss_dt)

    # Check gradients for differentiable logit tensors
    for k in grad_keys:
        assert model_out_dt[k].grad is not None, f"{k} gradient is None"
        grad_full = model_out_dt[k].grad.full_tensor()
        if expected_grads.get(k) is not None:
            torch.testing.assert_close(
                grad_full.cpu(),
                expected_grads[k],
                atol=grad_atol,
                rtol=grad_rtol,
                msg=lambda m: f"Rank {rank} {k} grad mismatch\n{m}",
            )
        # Non-vacuous
        assert grad_full.abs().sum() > 0, f"{k} gradient is all-zero"

    DistributedManager.cleanup()
    monkeypatch.undo()


# ---------------------------------------------------------------------------
# Parametrized test functions
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "setup_env",
    [
        # CPU dp=2 cp=3: DP + non-power-of-two CP for CPU-only CI
        ((2, 3), True, "cpu", "ENV"),
        # CUDA dp=1 cp=1: serial-equivalent sanity check (1 GPU)
        ((1, 1), True, "cuda", "ENV"),
        # CUDA dp=1 cp=2: CP-only (2 GPUs)
        ((1, 2), True, "cuda", "ENV"),
        # CUDA dp=1 cp=3: non-power-of-two CP on GPU (3 GPUs)
        ((1, 3), True, "cuda", "ENV"),
    ],
    indirect=("setup_env",),
    ids=["cpu-dp2-cp3", "cuda-dp1-cp1", "cuda-dp1-cp2", "cuda-dp1-cp3"],
)
@pytest.mark.parametrize("multiplicity", [1, 2], ids=["multiplicity=1", "multiplicity=2"])
@pytest.mark.parametrize("seed", [42, 99], ids=["seed=42", "seed=99"])
def test_dtensor_compute_frame_pred_1d(setup_env, multiplicity, seed):
    """1D CP compute_frame_pred: distributed frames_idx and mask_collinear match serial."""
    grid_group_sizes, world_size, device_type, backend, _, env_per_rank = setup_env
    skip_if_cuda_not_avail_or_device_count_less_than_word_size(device_type=device_type, world_size=world_size)

    cp_size = grid_group_sizes["cp"]
    batch_size = grid_group_sizes["dp"]
    n_tokens_per_rank = 20
    n_tokens = cp_size * n_tokens_per_rank
    max_atoms_per_token = 18
    n_atoms = n_tokens * max_atoms_per_token

    rng = torch.Generator()
    rng.manual_seed(seed)

    pred_atom_coords = torch.randn(batch_size * multiplicity, n_atoms, 3, generator=rng)
    # Enforce collinearity for some atoms so mask_collinear is non-trivial
    collinear_mask = torch.randint(0, 2, (batch_size * multiplicity, n_atoms), generator=rng, dtype=torch.bool)
    pred_atom_coords = torch.where(collinear_mask.unsqueeze(-1), pred_atom_coords, torch.zeros_like(pred_atom_coords))

    rng_features = torch.Generator()
    rng_features.manual_seed(seed)
    feats = random_features(
        size_batch=batch_size,
        n_tokens=n_tokens,
        n_atoms=n_atoms,
        n_msa=1,
        atom_counts_per_token_range=(1, max_atoms_per_token),
        device=torch.device("cpu"),
        float_value_range=(-1.0, 1.0),
        selected_keys=[
            "asym_id",
            "atom_to_token",
            "atom_pad_mask",
            "atom_resolved_mask",
            "frames_idx",
            "atom_counts_per_token",
            "mol_type",
            "token_pad_mask",
            "frame_resolved_mask",
        ],
        rng=rng_features,
    )
    # Cast float64 features to float32
    for k, v in feats.items():
        if v.dtype == torch.float64:
            feats[k] = v.float()

    # Validate frames_idx points to valid atoms
    atom_pad_mask_bool = feats["atom_pad_mask"].bool()
    frames_idx = feats["frames_idx"]
    atom_pad_per_token = atom_pad_mask_bool.unsqueeze(1).expand(-1, n_tokens, -1)
    frame_atom_valid = torch.gather(atom_pad_per_token, dim=2, index=frames_idx)
    assert torch.all(frame_atom_valid), "random_features generated frames_idx pointing to masked atoms"

    feats_serial = {
        "asym_id": feats["asym_id"],
        "atom_to_token": feats["atom_to_token"],
        "atom_pad_mask": feats["atom_pad_mask"],
        "atom_resolved_mask": feats["atom_resolved_mask"],
        "mol_type": feats["mol_type"],
        "token_pad_mask": feats["token_pad_mask"],
    }
    # compute_frame_pred calls torch.sort on dist_mat rows with near-ties; CPU and CUDA
    # use different tie-break orders, so we must compute the reference on the same device
    # as the distributed path it's compared against. The 1D-CP impl is bit-identical to a
    # CUDA reference (verified offline); divergence at default tol comes from CPU vs CUDA
    # torch.sort tie-break, not from the distributed implementation.
    ref_device = torch.device("cuda" if device_type == "cuda" else "cpu")
    expected_frames_idx, expected_mask_collinear = serial_compute_frame_pred(
        pred_atom_coords.to(ref_device),
        feats["frames_idx"].to(ref_device),
        {k: v.to(ref_device) for k, v in feats_serial.items()},
        multiplicity,
    )
    expected_frames_idx = expected_frames_idx.cpu()
    expected_mask_collinear = expected_mask_collinear.cpu()

    # Non-vacuous: mask_collinear should have some True entries on valid tokens
    token_pad_bool = feats["token_pad_mask"].bool()
    for batch_i in range(batch_size):
        valid = expected_mask_collinear[:, :, token_pad_bool[batch_i]]
        assert valid.any(), (
            f"batch {batch_i} expected_mask_collinear on valid tokens is always False — " "test would be vacuous"
        )

    payload = (
        grid_group_sizes,
        device_type,
        backend,
        env_per_rank,
        multiplicity,
        pred_atom_coords.detach().cpu(),
        {k: v.detach().cpu() for k, v in feats.items()},
        expected_frames_idx.detach().cpu(),
        expected_mask_collinear.detach().cpu(),
    )
    spawn_multiprocessing(_worker_compute_frame_pred_1d, world_size, payload)


@pytest.mark.parametrize(
    "setup_env",
    [
        # CPU dp=2 cp=3: DP + non-power-of-two CP for CPU-only CI
        ((2, 3), True, "cpu", "ENV"),
        # CUDA dp=1 cp=1: serial-equivalent sanity check (1 GPU)
        ((1, 1), True, "cuda", "ENV"),
        # CUDA dp=1 cp=2: CP-only (2 GPUs)
        ((1, 2), True, "cuda", "ENV"),
        # CUDA dp=1 cp=3: non-power-of-two CP on GPU (3 GPUs)
        ((1, 3), True, "cuda", "ENV"),
    ],
    indirect=("setup_env",),
    ids=["cpu-dp2-cp3", "cuda-dp1-cp1", "cuda-dp1-cp2", "cuda-dp1-cp3"],
)
@pytest.mark.parametrize(
    "atom_pl",
    [_ATOM, _ATOM_SHARDED],
    ids=["atom-replicated", "atom-sharded"],
)
def test_resolved_loss_1d_forward_backward(setup_env, atom_pl):
    """1D CP resolved loss: distributed loss and pred gradient match serial.

    The ``atom_pl`` axis exercises both supported atom placements: the canonical
    (Shard(0), Replicate()) and the post-694573d2 (Shard(0), Shard(1)). The latter
    triggers the wrapper-level redistribute introduced in this commit.
    """
    grid_group_sizes, world_size, device_type, backend, _, env_per_rank = setup_env
    skip_if_cuda_not_avail_or_device_count_less_than_word_size(device_type=device_type, world_size=world_size)

    multiplicity = 1
    feats, model_out, true_coords, true_coords_resolved_mask, d_loss = _generate_test_data(
        cp_size=grid_group_sizes["cp"], multiplicity=multiplicity
    )

    # Serial reference
    pred = model_out["resolved_logits"].clone().requires_grad_(True)
    serial_loss = serial_resolved_loss(
        pred,
        feats,
        true_coords_resolved_mask,
        token_level_confidence=True,
        multiplicity=multiplicity,
    )
    assert serial_loss.item() > 0, "Serial loss is zero — test is vacuous"
    serial_loss.backward(d_loss.clone())
    expected_grad = pred.grad.detach().cpu().clone()

    payload = (
        grid_group_sizes,
        device_type,
        backend,
        env_per_rank,
        model_out["resolved_logits"].detach().cpu(),
        {k: v.detach().cpu() for k, v in feats.items()},
        true_coords_resolved_mask.detach().cpu(),
        serial_loss.item(),
        expected_grad,
        d_loss.detach().cpu(),
        multiplicity,
        atom_pl,
    )
    spawn_multiprocessing(_worker_resolved_loss_1d, world_size, payload)


@pytest.mark.parametrize(
    "setup_env",
    [
        ((2, 3), True, "cpu", "ENV"),
        ((1, 1), True, "cuda", "ENV"),
        ((1, 2), True, "cuda", "ENV"),
        # CUDA dp=1 cp=3: non-power-of-two CP on GPU (3 GPUs)
        ((1, 3), True, "cuda", "ENV"),
    ],
    indirect=("setup_env",),
    ids=["cpu-dp2-cp3", "cuda-dp1-cp1", "cuda-dp1-cp2", "cuda-dp1-cp3"],
)
@pytest.mark.parametrize(
    "atom_pl",
    [_ATOM, _ATOM_SHARDED],
    ids=["atom-replicated", "atom-sharded"],
)
def test_plddt_loss_1d_forward_backward(setup_env, atom_pl):
    """1D CP pLDDT loss: distributed loss and pred gradient match serial.

    The ``atom_pl`` axis exercises both supported atom placements: the canonical
    (Shard(0), Replicate()) and the post-694573d2 (Shard(0), Shard(1)). The latter
    triggers the wrapper-level redistribute introduced in this commit.
    """
    grid_group_sizes, world_size, device_type, backend, _, env_per_rank = setup_env
    skip_if_cuda_not_avail_or_device_count_less_than_word_size(device_type=device_type, world_size=world_size)

    multiplicity = 1
    feats, model_out, true_coords, true_coords_resolved_mask, d_loss = _generate_test_data(
        cp_size=grid_group_sizes["cp"], multiplicity=multiplicity
    )

    pred = model_out["plddt_logits"].clone().requires_grad_(True)
    serial_loss_val, _ = serial_plddt_loss(
        pred,
        model_out["sample_atom_coords"],
        feats,
        true_coords,
        true_coords_resolved_mask,
        token_level_confidence=True,
        multiplicity=multiplicity,
    )
    assert serial_loss_val.item() > 0, "Serial plddt loss is zero — test is vacuous"
    serial_loss_val.backward(d_loss.clone())
    expected_grad = pred.grad.detach().cpu().clone()

    payload = (
        grid_group_sizes,
        device_type,
        backend,
        env_per_rank,
        model_out["plddt_logits"].detach().cpu(),
        model_out["sample_atom_coords"].detach().cpu(),
        true_coords.detach().cpu(),
        true_coords_resolved_mask.detach().cpu(),
        {k: v.detach().cpu() for k, v in feats.items()},
        serial_loss_val.item(),
        expected_grad,
        d_loss.detach().cpu(),
        multiplicity,
        atom_pl,
    )
    spawn_multiprocessing(_worker_plddt_loss_1d, world_size, payload)


def _inject_cross_shard_self_pairs(feats: dict, cp_size: int) -> dict:
    """Mutate ``r_set_to_rep_atom`` to install cross-shard self-pairs that
    the buggy intra-shard mask cannot catch.

    For every rank-0-local token ``t`` (i.e. ``t in [0, n_tokens // cp)``),
    we install one R-set entry on each higher-rank shard whose rep_atom
    matches token ``t``'s rep_atom. Specifically: for cp-rank ``r >= 1``,
    we override R-set entries
    ``r * (N_R // cp) .. r * (N_R // cp) + tokens_per_rank`` so each one
    points to a distinct rank-0 token's rep_atom. After distribution under
    (Shard(0), Shard(1)) those entries land on cp-rank ``r``, while the
    matching tokens live on cp-rank 0 — so every (token, R-set entry)
    match in this injected block is a cross-shard self-pair.

    The serial loss zeros all such pairs via
    ``pair_mask = pair_mask * (1 - eye)`` then projection through
    ``r_set_to_rep_atom``; the buggy distributed loss leaves them unmasked
    because it only zeros the intra-shard slice
    ``pair_mask[:, :, shard_start:shard_end]``.

    Because the injected rep_atom matches the LOCAL token's rep_atom on
    rank 0, the cdist contribution at that pair is exactly zero and the
    score saturates at 1.0 — so each unmasked injection adds 1 to both
    ``out_num`` and ``out_denom`` for the affected token, biasing
    ``target_lddt`` by ~1 / (out_denom + 1). With ``tokens_per_rank``
    injections per affected token across (cp-1) ranks, the bias is large
    enough to cross multiple ``floor(target_lddt * num_bins)`` boundaries
    and shift the cross-entropy loss far beyond the 0.01 atol budget.

    Returns
    -------
    dict
        The mutated ``feats`` (modified in place) — convenient for chaining.
    """
    t2ra = feats["token_to_rep_atom"]
    r2ra = feats["r_set_to_rep_atom"]
    n_tokens_total = t2ra.shape[1]
    n_r = r2ra.shape[1]
    tokens_per_rank = n_tokens_total // cp_size
    r_per_rank = n_r // cp_size

    # rank-0-local token indices: 0 .. tokens_per_rank - 1
    # Each gets one injected R-set entry per higher rank.
    rank0_token_idx = torch.arange(tokens_per_rank)
    rank0_rep_atoms = t2ra[:, rank0_token_idx, :].argmax(dim=-1)  # [B, tokens_per_rank]

    # Number of slots we can inject per non-zero rank: min(tokens_per_rank, r_per_rank).
    # In practice tokens_per_rank == n_tokens // cp_size and r_per_rank <= n_tokens // cp_size,
    # so we cap at r_per_rank.
    n_inject = min(tokens_per_rank, r_per_rank)

    for r in range(1, cp_size):
        base = r * r_per_rank
        # Override entries [base : base + n_inject] to point at rank-0 tokens' rep_atoms.
        r2ra[:, base : base + n_inject, :] = 0
        for j in range(n_inject):
            for b in range(r2ra.shape[0]):
                r2ra[b, base + j, rank0_rep_atoms[b, j]] = 1.0

    feats["token_to_rep_atom"] = t2ra
    feats["r_set_to_rep_atom"] = r2ra
    return feats


@pytest.mark.parametrize(
    "setup_env",
    [
        ((1, 2), True, "cuda", "ENV"),
        # CUDA dp=1 cp=3: non-power-of-two CP on GPU (3 GPUs).
        ((1, 3), True, "cuda", "ENV"),
        # CPU cell: non-power-of-two CP for CI coverage without GPUs.
        ((2, 3), True, "cpu", "ENV"),
    ],
    indirect=("setup_env",),
    ids=["cuda-dp1-cp2", "cuda-dp1-cp3", "cpu-dp2-cp3"],
)
def test_plddt_loss_1d_cross_shard_self_pair(setup_env):
    """Adversarial: cross-shard self-pair masking must match serial.

    This test guards the global-rep_atom self-pair masking in
    ``_PLDDTLoss1D.forward``. The pre-fix implementation only zeroed
    ``pair_mask[:, :, shard_start:shard_end]`` (the intra-shard slice of
    the R-set axis), so an R-set entry on rank ``r > 0`` whose rep_atom
    matches a local token's rep_atom on rank 0 was left unmasked. The
    serial loss zeros such pairs via the atom-level ``(1 - eye)`` and the
    subsequent projection through ``r_set_to_rep_atom``, so any retained
    pair contaminates ``out_denom`` / ``out_num`` and shifts
    ``target_lddt`` → ``pred_lddt`` cross-entropy.

    Only the ``atom-replicated`` ``atom_pl`` is exercised because the bug
    lives in the rep_atom masking, not the atom-coord placement; covering
    one atom_pl per cp configuration is sufficient.
    """
    grid_group_sizes, world_size, device_type, backend, _, env_per_rank = setup_env
    skip_if_cuda_not_avail_or_device_count_less_than_word_size(device_type=device_type, world_size=world_size)
    cp_size = grid_group_sizes["cp"]
    assert cp_size > 1, "Cross-shard test requires cp > 1"

    multiplicity = 1
    feats, model_out, true_coords, true_coords_resolved_mask, d_loss = _generate_test_data(
        cp_size=cp_size, multiplicity=multiplicity
    )

    feats = _inject_cross_shard_self_pairs(feats, cp_size=cp_size)

    # Sanity: after injection, at least one (token, R-set) global pair must
    # share a rep_atom — otherwise the test is vacuous.
    t2ra_check = feats["token_to_rep_atom"]
    r2ra_check = feats["r_set_to_rep_atom"]
    rep_token = t2ra_check.argmax(dim=-1)  # [B, N_tokens]
    rep_r = r2ra_check.argmax(dim=-1)  # [B, N_R]
    matches = (rep_token.unsqueeze(-1) == rep_r.unsqueeze(1)).sum().item()
    assert matches > 0, "Injection produced no rep_atom matches — test is vacuous"

    pred = model_out["plddt_logits"].clone().requires_grad_(True)
    serial_loss_val, _ = serial_plddt_loss(
        pred,
        model_out["sample_atom_coords"],
        feats,
        true_coords,
        true_coords_resolved_mask,
        token_level_confidence=True,
        multiplicity=multiplicity,
    )
    assert serial_loss_val.item() > 0, "Serial plddt loss is zero — test is vacuous"
    serial_loss_val.backward(d_loss.clone())
    expected_grad = pred.grad.detach().cpu().clone()

    payload = (
        grid_group_sizes,
        device_type,
        backend,
        env_per_rank,
        model_out["plddt_logits"].detach().cpu(),
        model_out["sample_atom_coords"].detach().cpu(),
        true_coords.detach().cpu(),
        true_coords_resolved_mask.detach().cpu(),
        {k: v.detach().cpu() for k, v in feats.items()},
        serial_loss_val.item(),
        expected_grad,
        d_loss.detach().cpu(),
        multiplicity,
        _ATOM,
    )
    spawn_multiprocessing(_worker_plddt_loss_1d, world_size, payload)


@pytest.mark.parametrize(
    "setup_env",
    [
        ((2, 3), True, "cpu", "ENV"),
        ((1, 1), True, "cuda", "ENV"),
        ((1, 2), True, "cuda", "ENV"),
        # CUDA dp=1 cp=3: non-power-of-two CP on GPU (3 GPUs)
        ((1, 3), True, "cuda", "ENV"),
    ],
    indirect=("setup_env",),
    ids=["cpu-dp2-cp3", "cuda-dp1-cp1", "cuda-dp1-cp2", "cuda-dp1-cp3"],
)
@pytest.mark.parametrize(
    "atom_pl",
    [_ATOM, _ATOM_SHARDED],
    ids=["atom-replicated", "atom-sharded"],
)
def test_pde_loss_1d_forward_backward(setup_env, atom_pl):
    """1D CP PDE loss: distributed loss and pred gradient match serial.

    The ``atom_pl`` axis exercises both supported atom placements: the canonical
    (Shard(0), Replicate()) and the post-694573d2 (Shard(0), Shard(1)). The latter
    triggers the wrapper-level redistribute introduced in this commit.
    """
    grid_group_sizes, world_size, device_type, backend, _, env_per_rank = setup_env
    skip_if_cuda_not_avail_or_device_count_less_than_word_size(device_type=device_type, world_size=world_size)

    multiplicity = 1
    feats, model_out, true_coords, true_coords_resolved_mask, d_loss = _generate_test_data(
        cp_size=grid_group_sizes["cp"], multiplicity=multiplicity
    )

    pred = model_out["pde_logits"].clone().requires_grad_(True)
    serial_loss_val, _ = serial_pde_loss(
        pred,
        model_out["sample_atom_coords"],
        feats,
        true_coords,
        true_coords_resolved_mask,
        multiplicity=multiplicity,
    )
    assert serial_loss_val.item() > 0, "Serial pde loss is zero — test is vacuous"
    serial_loss_val.backward(d_loss.clone())
    expected_grad = pred.grad.detach().cpu().clone()

    payload = (
        grid_group_sizes,
        device_type,
        backend,
        env_per_rank,
        model_out["pde_logits"].detach().cpu(),
        model_out["sample_atom_coords"].detach().cpu(),
        true_coords.detach().cpu(),
        true_coords_resolved_mask.detach().cpu(),
        {k: v.detach().cpu() for k, v in feats.items()},
        serial_loss_val.item(),
        expected_grad,
        d_loss.detach().cpu(),
        multiplicity,
        atom_pl,
    )
    spawn_multiprocessing(_worker_pde_loss_1d, world_size, payload)


@pytest.mark.parametrize(
    "setup_env",
    [
        ((2, 3), True, "cpu", "ENV"),
        ((1, 1), True, "cuda", "ENV"),
        ((1, 2), True, "cuda", "ENV"),
        # CUDA dp=1 cp=3: non-power-of-two CP on GPU (3 GPUs)
        ((1, 3), True, "cuda", "ENV"),
    ],
    indirect=("setup_env",),
    ids=["cpu-dp2-cp3", "cuda-dp1-cp1", "cuda-dp1-cp2", "cuda-dp1-cp3"],
)
@pytest.mark.parametrize(
    "atom_pl",
    [_ATOM, _ATOM_SHARDED],
    ids=["atom-replicated", "atom-sharded"],
)
def test_confidence_loss_1d_aggregator(setup_env, atom_pl):
    """1D CP confidence_loss_1d aggregator: matches serial confidence_loss.

    The ``atom_pl`` axis exercises both supported atom placements: the canonical
    (Shard(0), Replicate()) and the post-694573d2 (Shard(0), Shard(1)). The latter
    triggers the wrapper-level redistribute introduced in this commit.
    """
    grid_group_sizes, world_size, device_type, backend, _, env_per_rank = setup_env
    skip_if_cuda_not_avail_or_device_count_less_than_word_size(device_type=device_type, world_size=world_size)

    multiplicity = 1
    alpha_pae = 0.0  # PAE disabled for aggregator parity test
    feats, model_out, true_coords, true_coords_resolved_mask, d_loss = _generate_test_data(
        cp_size=grid_group_sizes["cp"], multiplicity=multiplicity
    )

    # Serial reference — make logit tensors require grad
    serial_model_out = {}
    grad_keys = ["plddt_logits", "pde_logits", "resolved_logits"]
    for k, v in model_out.items():
        if k in grad_keys:
            serial_model_out[k] = v.clone().requires_grad_(True)
        else:
            serial_model_out[k] = v.clone()

    serial_result = serial_confidence_loss(
        serial_model_out,
        feats,
        true_coords,
        true_coords_resolved_mask,
        token_level_confidence=True,
        multiplicity=multiplicity,
        alpha_pae=alpha_pae,
    )
    serial_loss = serial_result["loss"]
    assert serial_loss.item() > 0, "Serial confidence loss is zero — test is vacuous"
    serial_loss.backward(d_loss.clone())

    expected_grads = {}
    for k in grad_keys:
        expected_grads[k] = serial_model_out[k].grad.detach().cpu().clone()

    # Prepare model_out for distributed: mark logits as requires_grad
    model_out_host = {}
    for k, v in model_out.items():
        t = v.detach().cpu()
        if k in grad_keys:
            t = t.requires_grad_(True)
        model_out_host[k] = t

    payload = (
        grid_group_sizes,
        device_type,
        backend,
        env_per_rank,
        model_out_host,
        {k: v.detach().cpu() for k, v in feats.items()},
        true_coords.detach().cpu(),
        true_coords_resolved_mask.detach().cpu(),
        serial_loss.item(),
        expected_grads,
        d_loss.detach().cpu(),
        multiplicity,
        alpha_pae,
        atom_pl,
    )
    spawn_multiprocessing(_worker_confidence_loss_1d, world_size, payload)


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
